#macro NULL -10
#macro RIGHT 0
#macro UP 1
#macro LEFT 2
#macro DOWN 3
#macro INTERACT 4
#macro DODGE 5
#macro BLOCK 6
#macro PARRY 7
#macro ATTACK1 8
#macro ATTACK2 9
#macro ATTACK3 10
#macro ATTACK4 11
#macro ATTACK5 12
#macro s_ACTIVE 0
#macro s_IDLE 1
#macro s_MOVE 2
#macro s_DODGE 3
#macro s_INTERACT 4
#macro s_BLOCK 5
#macro s_PARRY 6
#macro s_ATTACK1 7
#macro s_ATTACK2 8
#macro s_ATTACK3 9
#macro s_ATTACK4 10
#macro s_ATTACK5 11
#macro s_DAMAGED 12
#macro s_STUNED 13
#macro CHAMBER 0
#macro RELOAD 7
