// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -8; // Character_obj
global.__objectDepths[1] = 0; // Enemy_obj
global.__objectDepths[2] = -5; // Boss_obj
global.__objectDepths[3] = 5; // Arrow_Block_Down_obj
global.__objectDepths[4] = 0; // Arrow_Block_Right_obj
global.__objectDepths[5] = 0; // Spooky_Tree_obj
global.__objectDepths[6] = 0; // Arrow_Block_Left_obj
global.__objectDepths[7] = 0; // Arrow_Block_Up_obj
global.__objectDepths[8] = 0; // Green_Tree_obj
global.__objectDepths[9] = 0; // Brown_Tree_obj
global.__objectDepths[10] = 0; // Emerald_Tree_obj
global.__objectDepths[11] = 0; // Red_Tree_obj
global.__objectDepths[12] = 0; // Yellow_Tree_obj
global.__objectDepths[13] = 0; // Flowerbed_Blue_obj
global.__objectDepths[14] = 0; // Flowerbed_Orange_obj
global.__objectDepths[15] = -1; // Player01_obj
global.__objectDepths[16] = 0; // Flowerbed_White_obj
global.__objectDepths[17] = 5; // Mounds_obj
global.__objectDepths[18] = -8; // Bat_obj
global.__objectDepths[19] = 0; // Wall_obj
global.__objectDepths[20] = -8; // Fishman_obj
global.__objectDepths[21] = 0; // Manison_v02_obj
global.__objectDepths[22] = 0; // GreBox_Collisions_obj
global.__objectDepths[23] = 0; // Invisible_Wall_obj
global.__objectDepths[24] = 1; // Gate_obj
global.__objectDepths[25] = 0; // Floor2_Wall_obj
global.__objectDepths[26] = 0; // Sign_obj
global.__objectDepths[27] = 0; // Shrine_Txt_obj
global.__objectDepths[28] = 0; // Flowerbed_Red_obj
global.__objectDepths[29] = 100; // Pond_obj
global.__objectDepths[30] = 0; // Mansion_v01_obj
global.__objectDepths[31] = 0; // Invisible_Sign_obj
global.__objectDepths[32] = 0; // Flwer_Txt_02_obj
global.__objectDepths[33] = 0; // Start_Office_obj
global.__objectDepths[34] = 0; // Floor2_Door_obj
global.__objectDepths[35] = 0; // Gate_Txt_obj
global.__objectDepths[36] = 0; // Flwer_Txt_01_obj
global.__objectDepths[37] = 0; // Flwer_Txt_03_obj
global.__objectDepths[38] = 0; // Start_Exit_obj
global.__objectDepths[39] = 0; // Start_Floor1_obj
global.__objectDepths[40] = 0; // Flwer_Txt_04_obj
global.__objectDepths[41] = 0; // Office_Gate_obj
global.__objectDepths[42] = 0; // Office_Start_obj
global.__objectDepths[43] = 0; // Combat_Gate_obj
global.__objectDepths[44] = 0; // Office_Storage_obj
global.__objectDepths[45] = 0; // Gate_Office_obj
global.__objectDepths[46] = 0; // Gate_Enemy1_obj
global.__objectDepths[47] = 0; // Gate_Enemy2_obj
global.__objectDepths[48] = 0; // Pit_Combat_obj
global.__objectDepths[49] = 0; // Gate_Pit_obj
global.__objectDepths[50] = 0; // Gate_Combat_obj
global.__objectDepths[51] = 0; // Pit_Switch_obj
global.__objectDepths[52] = 0; // Combat_Pit_obj
global.__objectDepths[53] = 0; // Switch_Pit_obj
global.__objectDepths[54] = 0; // Switch_Storage_obj
global.__objectDepths[55] = 0; // Enemy2_Enemy1_obj
global.__objectDepths[56] = 0; // Enemy1_Office_obj
global.__objectDepths[57] = 0; // Pit_Gate_obj
global.__objectDepths[58] = 0; // Exit_Start_obj
global.__objectDepths[59] = 0; // Door_Start_obj
global.__objectDepths[60] = 0; // Storage_Switch_obj
global.__objectDepths[61] = 0; // Exit_Floor1_obj
global.__objectDepths[62] = 0; // Storage_Office_obj
global.__objectDepths[63] = 0; // Door_Boss_obj
global.__objectDepths[64] = 0; // Combination_Puzzle_obj
global.__objectDepths[65] = 0; // Door_Next_obj
global.__objectDepths[66] = -3; // Candle_Red_obj
global.__objectDepths[67] = 0; // Key_obj
global.__objectDepths[68] = 0; // BigKey_obj
global.__objectDepths[69] = 0; // Gate_Puzzle_03_obj
global.__objectDepths[70] = -3; // Candle_Blue_obj
global.__objectDepths[71] = -3; // Candle_Orange_obj
global.__objectDepths[72] = -3; // Candle_White_obj
global.__objectDepths[73] = 0; // Gate_Puzzle_01_obj
global.__objectDepths[74] = 0; // Gate_Puzzle_02_obj
global.__objectDepths[75] = 0; // Small_obj
global.__objectDepths[76] = 0; // Gate_Puzzle_05_obj
global.__objectDepths[77] = 0; // Shrine_obj
global.__objectDepths[78] = 0; // Combat_Lock_obj
global.__objectDepths[79] = 5; // Pit_obj
global.__objectDepths[80] = 0; // Bullet_obj
global.__objectDepths[81] = 0; // Arrow_obj
global.__objectDepths[82] = 0; // Bullet_90_obj
global.__objectDepths[83] = 0; // SlowMo_Bullet_obj
global.__objectDepths[84] = 0; // Camera_obj
global.__objectDepths[85] = 0; // Init_Game_obj
global.__objectDepths[86] = 0; // Start_Menu_obj
global.__objectDepths[87] = 0; // Menu_obj
global.__objectDepths[88] = 0; // Small_Gate_obj
global.__objectDepths[89] = 0; // Projectile_obj
global.__objectDepths[90] = 0; // Metal_Box_obj
global.__objectDepths[91] = 5; // BloodPrint_obj
global.__objectDepths[92] = 5; // Pressure_Plate_obj
global.__objectDepths[93] = 0; // Crate01_obj
global.__objectDepths[94] = 0; // Gate_Puzzle_07_obj
global.__objectDepths[95] = 0; // Gate_Puzzle_06_obj
global.__objectDepths[96] = 0; // Gate_Puzzle_04_obj
global.__objectDepths[97] = 0; // Crate_Key_obj
global.__objectDepths[98] = 0; // Crate02_obj
global.__objectDepths[99] = 0; // Checkpoint_01_obj
global.__objectDepths[100] = -20; // Options_Menu_obj
global.__objectDepths[101] = 0; // Credits_obj
global.__objectDepths[102] = 0; // Track_Boss_obj
global.__objectDepths[103] = 0; // Track_Floor1_obj
global.__objectDepths[104] = 0; // Dialogue_obj
global.__objectDepths[105] = 0; // Track_Floor2_obj
global.__objectDepths[106] = 0; // Controls_Menu_obj
global.__objectDepths[107] = -10; // Player02_obj
global.__objectDepths[108] = 0; // Pause_obj
global.__objectDepths[109] = 0; // Speaker_obj
global.__objectDepths[110] = 0; // GrabArm_obj
global.__objectDepths[111] = 0; // EnemySpawn_obj
global.__objectDepths[112] = 1; // floor_obj
global.__objectDepths[113] = 0; // Door_Shut_obj
global.__objectDepths[114] = 0; // SwingArc_obj


global.__objectNames[0] = "Character_obj";
global.__objectNames[1] = "Enemy_obj";
global.__objectNames[2] = "Boss_obj";
global.__objectNames[3] = "Arrow_Block_Down_obj";
global.__objectNames[4] = "Arrow_Block_Right_obj";
global.__objectNames[5] = "Spooky_Tree_obj";
global.__objectNames[6] = "Arrow_Block_Left_obj";
global.__objectNames[7] = "Arrow_Block_Up_obj";
global.__objectNames[8] = "Green_Tree_obj";
global.__objectNames[9] = "Brown_Tree_obj";
global.__objectNames[10] = "Emerald_Tree_obj";
global.__objectNames[11] = "Red_Tree_obj";
global.__objectNames[12] = "Yellow_Tree_obj";
global.__objectNames[13] = "Flowerbed_Blue_obj";
global.__objectNames[14] = "Flowerbed_Orange_obj";
global.__objectNames[15] = "Player01_obj";
global.__objectNames[16] = "Flowerbed_White_obj";
global.__objectNames[17] = "Mounds_obj";
global.__objectNames[18] = "Bat_obj";
global.__objectNames[19] = "Wall_obj";
global.__objectNames[20] = "Fishman_obj";
global.__objectNames[21] = "Manison_v02_obj";
global.__objectNames[22] = "GreBox_Collisions_obj";
global.__objectNames[23] = "Invisible_Wall_obj";
global.__objectNames[24] = "Gate_obj";
global.__objectNames[25] = "Floor2_Wall_obj";
global.__objectNames[26] = "Sign_obj";
global.__objectNames[27] = "Shrine_Txt_obj";
global.__objectNames[28] = "Flowerbed_Red_obj";
global.__objectNames[29] = "Pond_obj";
global.__objectNames[30] = "Mansion_v01_obj";
global.__objectNames[31] = "Invisible_Sign_obj";
global.__objectNames[32] = "Flwer_Txt_02_obj";
global.__objectNames[33] = "Start_Office_obj";
global.__objectNames[34] = "Floor2_Door_obj";
global.__objectNames[35] = "Gate_Txt_obj";
global.__objectNames[36] = "Flwer_Txt_01_obj";
global.__objectNames[37] = "Flwer_Txt_03_obj";
global.__objectNames[38] = "Start_Exit_obj";
global.__objectNames[39] = "Start_Floor1_obj";
global.__objectNames[40] = "Flwer_Txt_04_obj";
global.__objectNames[41] = "Office_Gate_obj";
global.__objectNames[42] = "Office_Start_obj";
global.__objectNames[43] = "Combat_Gate_obj";
global.__objectNames[44] = "Office_Storage_obj";
global.__objectNames[45] = "Gate_Office_obj";
global.__objectNames[46] = "Gate_Enemy1_obj";
global.__objectNames[47] = "Gate_Enemy2_obj";
global.__objectNames[48] = "Pit_Combat_obj";
global.__objectNames[49] = "Gate_Pit_obj";
global.__objectNames[50] = "Gate_Combat_obj";
global.__objectNames[51] = "Pit_Switch_obj";
global.__objectNames[52] = "Combat_Pit_obj";
global.__objectNames[53] = "Switch_Pit_obj";
global.__objectNames[54] = "Switch_Storage_obj";
global.__objectNames[55] = "Enemy2_Enemy1_obj";
global.__objectNames[56] = "Enemy1_Office_obj";
global.__objectNames[57] = "Pit_Gate_obj";
global.__objectNames[58] = "Exit_Start_obj";
global.__objectNames[59] = "Door_Start_obj";
global.__objectNames[60] = "Storage_Switch_obj";
global.__objectNames[61] = "Exit_Floor1_obj";
global.__objectNames[62] = "Storage_Office_obj";
global.__objectNames[63] = "Door_Boss_obj";
global.__objectNames[64] = "Combination_Puzzle_obj";
global.__objectNames[65] = "Door_Next_obj";
global.__objectNames[66] = "Candle_Red_obj";
global.__objectNames[67] = "Key_obj";
global.__objectNames[68] = "BigKey_obj";
global.__objectNames[69] = "Gate_Puzzle_03_obj";
global.__objectNames[70] = "Candle_Blue_obj";
global.__objectNames[71] = "Candle_Orange_obj";
global.__objectNames[72] = "Candle_White_obj";
global.__objectNames[73] = "Gate_Puzzle_01_obj";
global.__objectNames[74] = "Gate_Puzzle_02_obj";
global.__objectNames[75] = "Small_obj";
global.__objectNames[76] = "Gate_Puzzle_05_obj";
global.__objectNames[77] = "Shrine_obj";
global.__objectNames[78] = "Combat_Lock_obj";
global.__objectNames[79] = "Pit_obj";
global.__objectNames[80] = "Bullet_obj";
global.__objectNames[81] = "Arrow_obj";
global.__objectNames[82] = "Bullet_90_obj";
global.__objectNames[83] = "SlowMo_Bullet_obj";
global.__objectNames[84] = "Camera_obj";
global.__objectNames[85] = "Init_Game_obj";
global.__objectNames[86] = "Start_Menu_obj";
global.__objectNames[87] = "Menu_obj";
global.__objectNames[88] = "Small_Gate_obj";
global.__objectNames[89] = "Projectile_obj";
global.__objectNames[90] = "Metal_Box_obj";
global.__objectNames[91] = "BloodPrint_obj";
global.__objectNames[92] = "Pressure_Plate_obj";
global.__objectNames[93] = "Crate01_obj";
global.__objectNames[94] = "Gate_Puzzle_07_obj";
global.__objectNames[95] = "Gate_Puzzle_06_obj";
global.__objectNames[96] = "Gate_Puzzle_04_obj";
global.__objectNames[97] = "Crate_Key_obj";
global.__objectNames[98] = "Crate02_obj";
global.__objectNames[99] = "Checkpoint_01_obj";
global.__objectNames[100] = "Options_Menu_obj";
global.__objectNames[101] = "Credits_obj";
global.__objectNames[102] = "Track_Boss_obj";
global.__objectNames[103] = "Track_Floor1_obj";
global.__objectNames[104] = "Dialogue_obj";
global.__objectNames[105] = "Track_Floor2_obj";
global.__objectNames[106] = "Controls_Menu_obj";
global.__objectNames[107] = "Player02_obj";
global.__objectNames[108] = "Pause_obj";
global.__objectNames[109] = "Speaker_obj";
global.__objectNames[110] = "GrabArm_obj";
global.__objectNames[111] = "EnemySpawn_obj";
global.__objectNames[112] = "floor_obj";
global.__objectNames[113] = "Door_Shut_obj";
global.__objectNames[114] = "SwingArc_obj";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for